version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: helmet
    versions:
    - 4.4.1
  - dependency-name: socket.io
    versions:
    - 3.1.0
  - dependency-name: lodash
    versions:
    - 4.17.20
